version: '3.8'

services:
  client:
    build: ./
    container_name: client
    networks:
      - task_manager_server_default
    env_file:
      - .env

networks:
  task_manager_server_default:
    external: true